id: 10053
name: Configuration Management Tools
items:
  - ansible/ansible
  - pulumi/pulumi
  - hashicorp/terraform
  - saltstack/salt
  - aws/aws-cdk
  - GoogleCloudPlatform/terraformer
  - itamae-kitchen/itamae
  - someengineering/resoto
  - aelsabbahy/goss
  - aws/copilot-cli
  - puppetlabs/puppet
  - chef/chef
