name: Surge PR Preview

on:
  pull_request_target:
    paths:
      - 'web/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Use Node.js 18
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install
        run: npm ci --prefer-offline --no-audit
      - name: Lint
        run: |
          npm run lint:ci
          npm run typecheck

  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Use Node.js 18
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install
        run: npm ci --prefer-offline --no-audit
      - name: Prefetch
        run: npm run prefetch
      - name: Build 🏗️
        env:
          SENTRY_DSN: https://ea6017f8ee534468b308a2a6c949895a@o226447.ingest.sentry.io/6588620
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          OSSINSIGHT_PREVIEW: true
        run: npm run build
      - name: Deploy to ossinsight.surge.sh 🚀
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          teardown: true
          build: echo 'Deployed to surge'
          dist: './web/build'