name: Verify API server

on:
  pull_request:
    paths:
      - 'packages/api-server/**'

defaults:
  run:
    shell: bash
    working-directory: packages/api-server

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.14.2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v18.12.0
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --strict-peer-dependencies

      - name: Verify Sources
        run: pnpm run test

      - name: Build Project
        run: pnpm run build:ts
